### ISSUE TITLE
Week 1 Review Ticket

### ISSUE THREAD

**Issue by yolandayangg** [SlimeyTurtles/jinjaturtles#10]
- [ ] Project Owner initial requirements and derivative tangibles
- [ ] Requirements and Jobs assigned to each individuals listed on Scrum Board, including at least one in progress task

**Comment by jm1021** [comment]
Cooking Club site.  Avinh sponsor/owner.  Cooking, meeting, and eating.  Made tickets off of original tickets.  Need to do some work on Tickets, think "Thing".   Flow, data diagrams.

1.8/2
