### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by yolandayangg** [SlimeyTurtles/jinjaturtles#13]
Team score: **1.9/2**

- [ ] Github licensing: MIT and input into Github
- [ ] Sponsor presentation: Layout of website, content with wireframe, club information and contact information.
- [ ] Hosting plan: Deployment through raspberry pi
- [ ] PII concerns: sponsor has no problem with personal information displayed
- [ ] 1st codes in Github

**Comment by jm1021** [comment]
Cooking club website.   Cooking and Contact.  The wire had theme and club information.

They are you using MIT license.  No reason.

Theme of Website is modern.   Center of club is Avinh favorites dish.   

Recipe categories.   Recipe uploading.   Contact sheet of how is joining of the club.

Two different workflows, member workflow.  New member workflow which ultimately leads to sign up.  

Encrypting database to protect information.  

Question about hosting plan.   They will host on their own hardware.  

Suggestion is to have a Photo Upload.

**Comment by CalissaT** [comment]
### Feedback received:
- Photo album where people can see the food
- People eating the food/cooking

***

### Idea of Crossover Website: 
- Keep yourself updated on lacrosse (games, events, etc)
- Sponsor wanted space to have sign up feature and photo uploading 
    - General information about team
- Based on DNHS Football/Volleyball Website

### Feedback given:
- Add stats if it's easy to access
- Provide opportunities for recruitment
    - Information about the player
        -  Stats
        - Photo
        - Where they are interested in going to
